# -*- coding: utf-8 -*-
"""Visualizing_Sales_Data_with_Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGyFZ8q-4qAO8nIqfVAUHmEX242FvXR3
"""

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!pip install kaggle  #Install the Kaggle library
!pip install seaborn

#Allows you to upload files from your local computer to the Colab environment
from google.colab import files

files.upload()

# Change permissions for greater security
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

#List the dataset files to verify that the CSV is available
!kaggle datasets files -d ricardom23/datasets-of-supermaket-sales

#Download only the CSV file, without downloading a ZIP
!kaggle datasets download -d ricardom23/datasets-of-supermaket-sales --file supermarket_sales.csv

#Load the CSV file into a Pandas DataFrame:
df = pd.read_csv("supermarket_sales.csv")
# Display the first rows of the dataset
df.head()

#Seperate Date in diferent columns for analysis
df['TheDate'] = pd.to_datetime(df['Date'])
df['Year'] = (df['TheDate']).dt.year
df['Month'] = (df['TheDate']).dt.month
df['Day'] = (df['TheDate']).dt.day
df['Id'] = df.index
df.head(6)

# Quick summary of the DataFrame.
#What's it for?
#Detecting null values ​​
#Checking data types
#Optimizing memory
df.info()

# Statistical summary of the numeric columns in a DataFrame.
df.describe()

# Count the number of null (NaN) values ​​in each column of a DataFrame.
df.isnull().sum()

#Count the number of unique values ​​in each column of a DataFrame.
df.nunique()

#Count the number of unique values ​​in a column or an entire DataFrame.
df['City'].nunique()

#  Count the frequency of each unique value in a column of a DataFrame.
df['City'].value_counts()

# In Matplotlib it is used to create pie charts (circular graphs)
plt.figure(figsize=(3, 3))
plt.pie(df['City'].value_counts(), labels=df['City'].value_counts().index, autopct='%1.1f%%')
plt.title('City Distribution')
plt.show()

df['Product line'].value_counts()

# Create bar charts showing frequency or count with the seaborn library
plt.figure(figsize=(3, 3))
sns.countplot(data=df, x='Product line')
plt.title('Distribution of Product line')
plt.xlabel('Product line')
plt.ylabel('Count')
plt.xticks(rotation=90)
plt.show()

# Create a bar chart from a DataFrame or Series
df.groupby("Month")['Quantity'].sum().plot(kind="bar",figsize=(3, 3))
plt.title('Number of products sold per month')
plt.ylabel('Quantity')

#  Store the extracted data in an SQLite database.
import sqlite3
# Connect or create the SQLite database

connection = sqlite3.connect('supermarket_sales.db')
df.to_sql('sales', connection, if_exists='replace', index=False)
connection.close()

# Close the connection
connection.close()

# Connect to the database
connection = sqlite3.connect('supermarket_sales.db')

# Read the data from the table
df_read = pd.read_sql('SELECT * FROM sales', connection)
# Display the data
print(df_read)

# Close the connection
connection.close()