# -*- coding: utf-8 -*-
"""Copia de Visualizing_Sales_Data_with_Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5rpOYk85Kl-ceTWtRGhEijYXfR2frh0
"""

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

!pip install kaggle  #Install the Kaggle library
!pip install seaborn

#Allows you to upload files from your local computer to the Colab environment
from google.colab import files

files.upload()

# Change permissions for greater security
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

#List the dataset files to verify that the CSV is available
!kaggle datasets files -d ricardom23/datasets-of-supermaket-sales

#Download only the CSV file, without downloading a ZIP
!kaggle datasets download -d ricardom23/datasets-of-supermaket-sales --file supermarket_sales.csv

class SupermarketSales:
  #Load the CSV file into a Pandas DataFrame:
    def __init__(self, file_path):
        self.df = pd.read_csv(file_path)

    def preprocess_data(self):
  #Seperate Date in diferent columns for analysis
          """Transforms the date into different columns for analysis."""
          self.df['TheDate'] = pd.to_datetime(self.df['Date'])
          self.df['Year'],self.df['Month'],self.df['Day']= self.df['TheDate'].dt.year,self.df['TheDate'].dt.month,self.df['TheDate'].dt.day
          self.df['Id'] = self.df.index

    def show_summary(self):
  # Quick summary of the DataFrame.
          """Displays information and statistics about the DataFrame."""
          print(self.df.info())
          print(self.df.describe())
          print(self.df.isnull().sum())
          print(self.df.nunique())

    def visualize_data(self):
   # Quick visualize data of the DataFrame.
          """Pie charts (circular graphs)."""
          plt.figure(figsize=(5, 5))
          plt.pie(self.df['City'].value_counts(), labels=self.df['City'].value_counts().index, autopct='%1.1f%%')
          plt.title('City Distribution')
          plt.show()
          """Create bar charts."""
          plt.figure(figsize=(5, 5))
          sns.countplot(data=self.df, x='Product line')
          plt.title('Distribution of Product line')
          plt.xlabel('Product line')
          plt.ylabel('Count')
          plt.xticks(rotation=90)
          plt.show()
          """Create a bar chart from a DataFrame or Series"""
          self.df.groupby("Month")['Quantity'].sum().plot(kind="bar",figsize=(3, 3))
          plt.title('Number of products sold per month')
          plt.ylabel('Quantity')

    def store_to_db(self, db_name='supermarket_sales.db'):
   #  Store the extracted data in an SQLite database.
          """Save the data to a SQLite database."""
          connection = sqlite3.connect(db_name)
          self.df.to_sql('sales', connection, if_exists='replace', index=False)
          connection.close()

    def database_query_to_db(self, db_name='supermarket_sales.db'):
    #  Query the extracted data in an SQLite database.
            """Query the data to a SQLite database."""
            connection = sqlite3.connect(db_name)
            self.df_read = pd.read_sql('SELECT * FROM sales', connection)
            print(self.df_read)
            connection.close()

sales = SupermarketSales("supermarket_sales.csv")
sales.preprocess_data()
sales.show_summary()
sales.visualize_data()
sales.store_to_db()
sales.database_query_to_db()